package com.xiaobaobao.demo.model.sys.base;

import com.alibaba.fastjson.annotation.JSONField;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setAccount(String account) {
		set("account", account);
	}

	public String getAccount() {
		return get("account");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	@JSONField(serialize=false)
	public String getPassword() {
		return get("password");
	}

}
